{
  "Header": {
    "Original": "CVE-2023-40550 (An out-of-bounds read flaw was found in Shim when it tried to validate ...)",
    "ID": "CVE-2023-40550",
    "Description": "(An out-of-bounds read flaw was found in Shim when it tried to validate ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3813-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3813-1"
      ]
    },
    {
      "Original": "- shim 15.8-1 (bug #1061519)",
      "Type": "package",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1",
      "BugNo": 1061519
    },
    {
      "Original": "[bookworm] - shim 15.8-1~deb12u1",
      "Type": "package",
      "Release": "bookworm",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1~deb12u1"
    },
    {
      "Original": "[bullseye] - shim 15.8-1~deb11u1",
      "Type": "package",
      "Release": "bullseye",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1~deb11u1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2259915",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2259915"
    },
    {
      "Original": "NOTE: https://github.com/rhboot/shim/commit/93ce2552f3e9f71f888a672913bfc0eef255c56d (15.8)",
      "Type": "NOTE",
      "Description": "https://github.com/rhboot/shim/commit/93ce2552f3e9f71f888a672913bfc0eef255c56d (15.8)"
    },
    {
      "Original": "NOTE: Followup: https://github.com/rhboot/shim/commit/e7f5fdf53ee68025f3ef2688e2f27ccb0082db83 (15.8)",
      "Type": "NOTE",
      "Description": "Followup: https://github.com/rhboot/shim/commit/e7f5fdf53ee68025f3ef2688e2f27ccb0082db83 (15.8)"
    }
  ]
}