{
  "Header": {
    "Original": "CVE-2023-46446 (An issue in AsyncSSH before 2.14.1 allows attackers to control the rem ...)",
    "ID": "CVE-2023-46446",
    "Description": "(An issue in AsyncSSH before 2.14.1 allows attackers to control the rem ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3899-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3899-1"
      ]
    },
    {
      "Original": "- python-asyncssh 2.15.0-1 (bug #1055999)",
      "Type": "package",
      "Package": "python-asyncssh",
      "Kind": "fixed",
      "Version": "2.15.0-1",
      "BugNo": 1055999
    },
    {
      "Original": "[bookworm] - python-asyncssh \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-asyncssh",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - python-asyncssh \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "buster",
      "Package": "python-asyncssh",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/ronf/asyncssh/security/advisories/GHSA-c35q-ffpf-5qpm",
      "Type": "NOTE",
      "Description": "https://github.com/ronf/asyncssh/security/advisories/GHSA-c35q-ffpf-5qpm"
    },
    {
      "Original": "NOTE: https://github.com/ronf/asyncssh/commit/83e43f5ea3470a8617fc388c72b062c7136efd7e (v2.14.1)",
      "Type": "NOTE",
      "Description": "https://github.com/ronf/asyncssh/commit/83e43f5ea3470a8617fc388c72b062c7136efd7e (v2.14.1)"
    },
    {
      "Original": "NOTE: https://terrapin-attack.com/",
      "Type": "NOTE",
      "Description": "https://terrapin-attack.com/"
    }
  ]
}