{
  "Header": {
    "Original": "CVE-2023-40549 (An out-of-bounds read flaw was found in Shim due to the lack of proper ...)",
    "ID": "CVE-2023-40549",
    "Description": "(An out-of-bounds read flaw was found in Shim due to the lack of proper ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-3813-1}",
      "Type": "xref",
      "Bugs": [
        "DLA-3813-1"
      ]
    },
    {
      "Original": "- shim 15.8-1 (bug #1061519)",
      "Type": "package",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1",
      "BugNo": 1061519
    },
    {
      "Original": "[bookworm] - shim 15.8-1~deb12u1",
      "Type": "package",
      "Release": "bookworm",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1~deb12u1"
    },
    {
      "Original": "[bullseye] - shim 15.8-1~deb11u1",
      "Type": "package",
      "Release": "bullseye",
      "Package": "shim",
      "Kind": "fixed",
      "Version": "15.8-1~deb11u1"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2241797",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2241797"
    },
    {
      "Original": "NOTE: https://github.com/rhboot/shim/commit/afdc5039de0a4a3a40162a32daa070f94a883f09 (15.8)",
      "Type": "NOTE",
      "Description": "https://github.com/rhboot/shim/commit/afdc5039de0a4a3a40162a32daa070f94a883f09 (15.8)"
    }
  ]
}