{
  "Header": {
    "Original": "CVE-2023-6110 (A flaw was found in OpenStack. When a user tries to delete a non-exist ...)",
    "ID": "CVE-2023-6110",
    "Description": "(A flaw was found in OpenStack. When a user tries to delete a non-exist ...)"
  },
  "Annotations": [
    {
      "Original": "- python-openstackclient 6.3.0-2",
      "Type": "package",
      "Package": "python-openstackclient",
      "Kind": "fixed",
      "Version": "6.3.0-2"
    },
    {
      "Original": "[bookworm] - python-openstackclient \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python-openstackclient",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[bullseye] - python-openstackclient \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "python-openstackclient",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - python-openstackclient \u003cnot-affected\u003e (app cred access rules introduced in v5)",
      "Type": "package",
      "Release": "buster",
      "Package": "python-openstackclient",
      "Kind": "not-affected",
      "Description": "app cred access rules introduced in v5"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2212960",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2212960"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2209607",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2209607"
    },
    {
      "Original": "NOTE: https://review.opendev.org/888697",
      "Type": "NOTE",
      "Description": "https://review.opendev.org/888697"
    }
  ]
}