{
  "Header": {
    "Original": "CVE-2024-3219 (The  \\u201csocket\\u201d module provides a pure-Python fallback to the  ...)",
    "ID": "CVE-2024-3219",
    "Description": "(The  \\u201csocket\\u201d module provides a pure-Python fallback to the  ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.12 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.11 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.9 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python2.7 \u003cnot-affected\u003e (Vulnerable code not present)",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/122134",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/122134"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/122133",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/122133"
    },
    {
      "Original": "NOTE: https://www.openwall.com/lists/oss-security/2024/07/29/3",
      "Type": "NOTE",
      "Description": "https://www.openwall.com/lists/oss-security/2024/07/29/3"
    },
    {
      "Original": "NOTE: 3.9-branch: https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20",
      "Type": "NOTE",
      "Description": "3.9-branch: https://github.com/python/cpython/commit/06fa244666ec6335a3b9bf2367e31b42b9a89b20"
    },
    {
      "Original": "NOTE: 3.10-branch: https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2",
      "Type": "NOTE",
      "Description": "3.10-branch: https://github.com/python/cpython/commit/0b65c8bf5367625673eafb92f85046a1b31259f2"
    },
    {
      "Original": "NOTE: 3.11-branch: https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929",
      "Type": "NOTE",
      "Description": "3.11-branch: https://github.com/python/cpython/commit/5f90abaa786f994db3907fc31e2ee00ea2cf0929"
    },
    {
      "Original": "NOTE: 3.12-branch: https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c",
      "Type": "NOTE",
      "Description": "3.12-branch: https://github.com/python/cpython/commit/220e31adeaaa8436c9ff234cba1398bc49e2bb6c"
    },
    {
      "Original": "NOTE: 3.13-branch: https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54",
      "Type": "NOTE",
      "Description": "3.13-branch: https://github.com/python/cpython/commit/b252317956b7fc035bb3774ef6a177e227f9fc54"
    },
    {
      "Original": "NOTE: Only affects plattforms which do not support AF_UNIX.",
      "Type": "NOTE",
      "Description": "Only affects plattforms which do not support AF_UNIX."
    }
  ]
}