{
  "Header": {
    "Original": "CVE-2024-56072 (An issue was discovered in FastNetMon Community Edition through 1.2.7. ...)",
    "ID": "CVE-2024-56072",
    "Description": "(An issue was discovered in FastNetMon Community Edition through 1.2.7. ...)"
  },
  "Annotations": [
    {
      "Original": "- fastnetmon 1.2.8-1 (bug #1090388)",
      "Type": "package",
      "Package": "fastnetmon",
      "Kind": "fixed",
      "Version": "1.2.8-1",
      "BugNo": 1090388
    },
    {
      "Original": "NOTE: https://github.com/pavel-odintsov/fastnetmon/commit/5164a29603fff9dd445b7660a35090989f005000 (v1.2.8)",
      "Type": "NOTE",
      "Description": "https://github.com/pavel-odintsov/fastnetmon/commit/5164a29603fff9dd445b7660a35090989f005000 (v1.2.8)"
    },
    {
      "Original": "NOTE: https://github.com/pavel-odintsov/fastnetmon/commit/65c40ee92dd5bcad1ab52cbafa1afd62cf669e48 (v1.2.8)",
      "Type": "NOTE",
      "Description": "https://github.com/pavel-odintsov/fastnetmon/commit/65c40ee92dd5bcad1ab52cbafa1afd62cf669e48 (v1.2.8)"
    }
  ]
}