{
  "Header": {
    "Original": "CVE-2024-3220 (There is a defect in the CPython standard library module \\u201cmimetyp ...)",
    "ID": "CVE-2024-3220",
    "Description": "(There is a defect in the CPython standard library module \\u201cmimetyp ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.12 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.11 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "- python3.9 \u003cnot-affected\u003e (Windows-specific)",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "not-affected",
      "Description": "Windows-specific"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/CDXW34ND2LSAOYAR5N6UNONP4ZBX4D6R/"
    }
  ]
}