{
  "Header": {
    "Original": "CVE-2024-0690 (An information disclosure flaw was found in ansible-core due to a fail ...)",
    "ID": "CVE-2024-0690",
    "Description": "(An information disclosure flaw was found in ansible-core due to a fail ...)"
  },
  "Annotations": [
    {
      "Original": "- ansible-core 2.16.5-1 (bug #1061156)",
      "Type": "package",
      "Package": "ansible-core",
      "Kind": "fixed",
      "Version": "2.16.5-1",
      "BugNo": 1061156
    },
    {
      "Original": "[bookworm] - ansible-core 2.14.16-0+deb12u1",
      "Type": "package",
      "Release": "bookworm",
      "Package": "ansible-core",
      "Kind": "fixed",
      "Version": "2.14.16-0+deb12u1"
    },
    {
      "Original": "- ansible 5.4.0-1",
      "Type": "package",
      "Package": "ansible",
      "Kind": "fixed",
      "Version": "5.4.0-1"
    },
    {
      "Original": "[bullseye] - ansible \u003cno-dsa\u003e (Minor issue)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "ansible",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: ansible-core was split off from src:ansible with 4.6.0-1 in experimental/5.4.0-1 in sid",
      "Type": "NOTE",
      "Description": "ansible-core was split off from src:ansible with 4.6.0-1 in experimental/5.4.0-1 in sid"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2259013",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2259013"
    },
    {
      "Original": "NOTE: https://github.com/ansible/ansible/pull/82565",
      "Type": "NOTE",
      "Description": "https://github.com/ansible/ansible/pull/82565"
    },
    {
      "Original": "NOTE: https://github.com/ansible/ansible/commit/beb04bc2642c208447c5a936f94310528a1946b1 (v2.14.14rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/ansible/ansible/commit/beb04bc2642c208447c5a936f94310528a1946b1 (v2.14.14rc1)"
    }
  ]
}