{
  "Header": {
    "Original": "CVE-2024-27281 (An issue was discovered in RDoc 6.3.3 through 6.6.2, as distributed in ...)",
    "ID": "CVE-2024-27281",
    "Description": "(An issue was discovered in RDoc 6.3.3 through 6.6.2, as distributed in ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-5677-1 DLA-3858-1}",
      "Type": "xref",
      "Bugs": [
        "DSA-5677-1",
        "DLA-3858-1"
      ]
    },
    {
      "Original": "- ruby3.2 \u003cunfixed\u003e (bug #1067802)",
      "Type": "package",
      "Package": "ruby3.2",
      "Kind": "unfixed",
      "BugNo": 1067802
    },
    {
      "Original": "- ruby3.1 \u003cunfixed\u003e (bug #1067803)",
      "Type": "package",
      "Package": "ruby3.1",
      "Kind": "unfixed",
      "BugNo": 1067803
    },
    {
      "Original": "- ruby2.7 \u003cremoved\u003e",
      "Type": "package",
      "Package": "ruby2.7",
      "Kind": "removed"
    },
    {
      "Original": "- ruby2.5 \u003cremoved\u003e",
      "Type": "package",
      "Package": "ruby2.5",
      "Kind": "removed"
    },
    {
      "Original": "NOTE: https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/",
      "Type": "NOTE",
      "Description": "https://www.ruby-lang.org/en/news/2024/03/21/rce-rdoc-cve-2024-27281/"
    },
    {
      "Original": "NOTE: https://github.com/ruby/rdoc/commit/da7a0c7553ef7250ca665a3fecdc01dbaacbb43d (v6.6.3)",
      "Type": "NOTE",
      "Description": "https://github.com/ruby/rdoc/commit/da7a0c7553ef7250ca665a3fecdc01dbaacbb43d (v6.6.3)"
    },
    {
      "Original": "NOTE: Follow-up: https://github.com/ruby/rdoc/commit/e4a0e71e6f1032f8b4e5e58b4ef60d702c22ce17 (v6.6.3.1)",
      "Type": "NOTE",
      "Description": "Follow-up: https://github.com/ruby/rdoc/commit/e4a0e71e6f1032f8b4e5e58b4ef60d702c22ce17 (v6.6.3.1)"
    }
  ]
}