{
  "Header": {
    "Original": "CVE-2024-7592 (There is a LOW severity vulnerability affecting CPython, specifically  ...)",
    "ID": "CVE-2024-7592",
    "Description": "(There is a LOW severity vulnerability affecting CPython, specifically  ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.13 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "python3.13",
      "Kind": "unfixed"
    },
    {
      "Original": "- python3.12 \u003cunfixed\u003e",
      "Type": "package",
      "Package": "python3.12",
      "Kind": "unfixed"
    },
    {
      "Original": "- python3.11 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.11",
      "Kind": "removed"
    },
    {
      "Original": "[bookworm] - python3.11 \u003cpostponed\u003e (Minor issue, wait until merged into 3.11 branch)",
      "Type": "package",
      "Release": "bookworm",
      "Package": "python3.11",
      "Kind": "postponed",
      "Description": "Minor issue, wait until merged into 3.11 branch"
    },
    {
      "Original": "- python3.9 \u003cremoved\u003e",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "removed"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/pull/123075",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/pull/123075"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/issues/123067",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/issues/123067"
    },
    {
      "Original": "NOTE: https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/",
      "Type": "NOTE",
      "Description": "https://mail.python.org/archives/list/security-announce@python.org/thread/HXJAAAALNUNGCQUS2W7WR6GFIZIHFOOK/"
    }
  ]
}