{
  "Header": {
    "Original": "CVE-2024-0217 (A use-after-free flaw was found in PackageKitd. In some conditions, th ...)",
    "ID": "CVE-2024-0217",
    "Description": "(A use-after-free flaw was found in PackageKitd. In some conditions, th ...)"
  },
  "Annotations": [
    {
      "Original": "NOTE: Unclear CVE assignment for packagekit, it was never clarified what is was about (see also #1060016)",
      "Type": "NOTE",
      "Description": "Unclear CVE assignment for packagekit, it was never clarified what is was about (see also #1060016)"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2256624",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2256624"
    }
  ]
}