{
  "Header": {
    "Original": "CVE-2024-4109 (A flaw was found in Undertow. An HTTP request header value from a prev ...)",
    "ID": "CVE-2024-4109",
    "Description": "(A flaw was found in Undertow. An HTTP request header value from a prev ...)"
  },
  "Annotations": [
    {
      "Original": "- undertow \u003cunfixed\u003e (unimportant)",
      "Type": "package",
      "Package": "undertow",
      "Kind": "unfixed",
      "Severity": "unimportant"
    },
    {
      "Original": "NOTE: https://bugzilla.redhat.com/show_bug.cgi?id=2272325",
      "Type": "NOTE",
      "Description": "https://bugzilla.redhat.com/show_bug.cgi?id=2272325"
    },
    {
      "Original": "NOTE: https://github.com/undertow-io/undertow/pull/1668",
      "Type": "NOTE",
      "Description": "https://github.com/undertow-io/undertow/pull/1668"
    },
    {
      "Original": "NOTE: https://issues.redhat.com/browse/UNDERTOW-2451",
      "Type": "NOTE",
      "Description": "https://issues.redhat.com/browse/UNDERTOW-2451"
    },
    {
      "Original": "NOTE: Marked upstream as 'not a bug' given there are no leakages in the classes",
      "Type": "NOTE",
      "Description": "Marked upstream as 'not a bug' given there are no leakages in the classes"
    },
    {
      "Original": "NOTE: covered by the pull request #1668 upstream. No security impact.",
      "Type": "NOTE",
      "Description": "covered by the pull request #1668 upstream. No security impact."
    }
  ]
}