{
  "Header": {
    "Original": "CVE-2020-27619 (In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)",
    "ID": "CVE-2020-27619",
    "Description": "(In Python 3 through 3.9.0, the Lib/test/multibytecodec_support.py CJK  ...)"
  },
  "Annotations": [
    {
      "Original": "- python3.9 3.9.1~rc1-1 (unimportant)",
      "Type": "package",
      "Package": "python3.9",
      "Kind": "fixed",
      "Version": "3.9.1~rc1-1",
      "Severity": "unimportant"
    },
    {
      "Original": "- python3.8 3.8.7~rc1-1 (unimportant)",
      "Type": "package",
      "Package": "python3.8",
      "Kind": "fixed",
      "Version": "3.8.7~rc1-1",
      "Severity": "unimportant"
    },
    {
      "Original": "- python3.7 \u003cremoved\u003e (unimportant)",
      "Type": "package",
      "Package": "python3.7",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "- python2.7 \u003cremoved\u003e (unimportant)",
      "Type": "package",
      "Package": "python2.7",
      "Kind": "removed",
      "Severity": "unimportant"
    },
    {
      "Original": "- pypy3 7.3.5+dfsg-2",
      "Type": "package",
      "Package": "pypy3",
      "Kind": "fixed",
      "Version": "7.3.5+dfsg-2"
    },
    {
      "Original": "NOTE: https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html",
      "Type": "NOTE",
      "Description": "https://python-security.readthedocs.io/vuln/cjk-codec-download-eval.html"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/2ef5caa58febc8968e670e39e3d37cf8eef3cab8 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/a8bf44d04915f7366d9f8dfbf84822ac37a4bab3 (master)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (v3.9.1rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/b664a1df4ee71d3760ab937653b10997081b1794 (v3.9.1rc1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (v3.8.7rc1)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/6c6c256df3636ff6f6136820afaefa5a10a3ac33 (v3.8.7rc1)"
    },
    {
      "Original": "NOTE: https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (v3.7.10)",
      "Type": "NOTE",
      "Description": "https://github.com/python/cpython/commit/43e523103886af66d6c27cd72431b5d9d14cd2a9 (v3.7.10)"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue41944",
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue41944"
    },
    {
      "Original": "NOTE: Only affects the testsuite",
      "Type": "NOTE",
      "Description": "Only affects the testsuite"
    }
  ]
}