{
  "Header": {
    "Original": "CVE-2025-2148 (A vulnerability was found in PyTorch 2.6.0+cu124. It has been declared ...)",
    "ID": "CVE-2025-2148",
    "Description": "(A vulnerability was found in PyTorch 2.6.0+cu124. It has been declared ...)"
  },
  "Annotations": [
    {
      "Original": "- pytorch \u003cunfixed\u003e",
      "Type": "package",
      "Package": "pytorch",
      "Kind": "unfixed"
    },
    {
      "Original": "NOTE: https://github.com/pytorch/pytorch/issues/147722",
      "Type": "NOTE",
      "Description": "https://github.com/pytorch/pytorch/issues/147722"
    }
  ]
}