{
  "Header": {
    "Original": "CVE-2021-31239 (An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacke ...)",
    "ID": "CVE-2021-31239",
    "Description": "(An issue found in SQLite SQLite3 v.3.35.4 that allows a remote attacke ...)"
  },
  "Annotations": [
    {
      "Original": "- sqlite3 3.36.0-2",
      "Type": "package",
      "Package": "sqlite3",
      "Kind": "fixed",
      "Version": "3.36.0-2"
    },
    {
      "Original": "[bullseye] - sqlite3 \u003cnot-affected\u003e (Vulnerable code not present)",
      "Type": "package",
      "Release": "bullseye",
      "Package": "sqlite3",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "[buster] - sqlite3 \u003cnot-affected\u003e (Vulnerable code not present)",
      "Type": "package",
      "Release": "buster",
      "Package": "sqlite3",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "- sqlite \u003cnot-affected\u003e (Vulnerable code not present)",
      "Type": "package",
      "Package": "sqlite",
      "Kind": "not-affected",
      "Description": "Vulnerable code not present"
    },
    {
      "Original": "NOTE: https://www.sqlite.org/forum/forumpost/d9fce1a89b",
      "Type": "NOTE",
      "Description": "https://www.sqlite.org/forum/forumpost/d9fce1a89b"
    },
    {
      "Original": "NOTE: Fixed by: https://github.com/sqlite/sqlite/commit/6536c4f18e3dd37084c902f965631ff28248d8c7 (version-3.36.0)",
      "Type": "NOTE",
      "Description": "Fixed by: https://github.com/sqlite/sqlite/commit/6536c4f18e3dd37084c902f965631ff28248d8c7 (version-3.36.0)"
    },
    {
      "Original": "NOTE: Introduced by: https://sqlite.org/src/info/25c3186aa143328157fb506a29802e87099cd14be4fa218230484a3212f20621 (3.35.2)",
      "Type": "NOTE",
      "Description": "Introduced by: https://sqlite.org/src/info/25c3186aa143328157fb506a29802e87099cd14be4fa218230484a3212f20621 (3.35.2)"
    }
  ]
}